# Generated by Django 5.2.1 on 2025-08-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_product_carts_count_product_rating_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
