# Generated by Django 5.2.1 on 2025-08-23 14:14

import django.db.models.deletion
import ecommerceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_product_hot_deal_product_hot_deal_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerceapp.models.offer_upload)),
                ('badge', models.CharField(blank=True, default='LIMITED TIME', max_length=60)),
                ('cta_label', models.CharField(blank=True, default='Shop Now', max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('default_limit', models.PositiveIntegerField(default=12)),
                ('default_order', models.CharField(default='-created_at', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, to='ecommerceapp.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('limit', models.PositiveIntegerField(default=8)),
                ('view_all_link', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grids', to='ecommerceapp.productcollection')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
