# Generated by Django 5.2.1 on 2025-08-23 18:09

import django.db.models.deletion
import ecommerceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_specialoffer_productcollection_productgrid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgrid',
            options={},
        ),
        migrations.RemoveField(
            model_name='productgrid',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productgrid',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='productgrid',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='productgrid',
            name='view_all_link',
        ),
        migrations.AddField(
            model_name='productgrid',
            name='badge',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productgrid',
            name='discount_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productgrid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerceapp.models.prod_upload),
        ),
        migrations.AddField(
            model_name='productgrid',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productgrid',
            name='original_price_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productgrid',
            name='price_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='productgrid',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_items', to='ecommerceapp.product'),
        ),
        migrations.AddField(
            model_name='productgrid',
            name='sort',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='productgrid',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
