# Generated by Django 5.2.1 on 2025-08-30 15:15

import ecommerceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_productgrid_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], db_index=True, default='top', max_length=10)),
                ('variant', models.CharField(choices=[('default', 'Default'), ('coupon', 'Coupon'), ('clearance', 'Clearance')], db_index=True, default='default', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerceapp.models.promo_upload)),
                ('image_url', models.URLField(blank=True)),
                ('class_name', models.CharField(blank=True, max_length=300)),
                ('overlay_class', models.CharField(blank=True, max_length=300)),
                ('is_wide', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('coupon_text', models.CharField(blank=True, max_length=160)),
                ('offer_text', models.CharField(blank=True, max_length=160)),
                ('main_offer', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['sort', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'variant'], name='ecommerceap_placeme_589030_idx'), models.Index(fields=['is_active'], name='ecommerceap_is_acti_d7e815_idx'), models.Index(fields=['starts_at', 'ends_at'], name='ecommerceap_starts__a87a2a_idx')],
            },
        ),
    ]
