# Generated by Django 5.2.1 on 2025-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_promobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='variant',
            field=models.CharField(choices=[('default', 'Default'), ('coupon', 'Coupon'), ('clearance', 'Clearance')], db_index=True, default='default', max_length=20),
        ),
    ]
