# Generated by Django 5.2.1 on 2025-09-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_alter_promobanner_title_alter_promobanner_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('card', 'Card'), ('bank-transfer', 'Bank Transfer'), ('cash-on-delivery', 'Cash on Delivery')], max_length=30)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='INR', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='ecommerceapp.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
