# Generated by Django 5.2.1 on 2025-09-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_color_store_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_uom',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('G', 'Grams'), ('KG', 'Kilograms'), ('ML', 'Milliliters'), ('L', 'Liters'), ('BUNDLE', 'Bundle / Pack')], default='KG', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_country',
            field=models.CharField(blank=True, default='IN', max_length=60),
        ),
    ]
