# Generated by Django 5.2.1 on 2025-09-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_product_is_published_alter_product_default_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_facts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(blank=True, max_length=60)),
                ('is_highlight', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='ecommerceapp.product')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['product', 'group'], name='ecommerceap_product_aae370_idx'), models.Index(fields=['product', 'name'], name='ecommerceap_product_69ea67_idx')],
            },
        ),
    ]
