# Generated by Django 5.2.1 on 2025-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_product_allergens_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['sort_order', 'group', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='productspecification',
            name='ecommerceap_product_aae370_idx',
        ),
        migrations.RemoveIndex(
            model_name='productspecification',
            name='ecommerceap_product_69ea67_idx',
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'group', 'name')},
        ),
    ]
