# Generated by Django 5.2.1 on 2025-09-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0015_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
