# Generated by Django 5.2.1 on 2025-10-06 12:39

import ecommerceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0016_productreview_user_email_productreview_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Industry Recognition', 'Industry Recognition'), ('Sustainability', 'Sustainability'), ('Social Impact', 'Social Impact'), ('Customer Excellence', 'Customer Excellence'), ('Innovation', 'Innovation'), ('Quality', 'Quality')], default='Industry Recognition', max_length=64)),
                ('emblem', models.ImageField(blank=True, null=True, upload_to=ecommerceapp.models._upload_awards)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort'], name='ecommerceap_is_acti_4a5047_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('authority', models.CharField(blank=True, max_length=200)),
                ('valid_until', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort'], name='ecommerceap_is_acti_1fb74e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Farming & Agriculture', 'Farming & Agriculture'), ('Events & Workshops', 'Events & Workshops'), ('Certifications', 'Certifications'), ('Community Impact', 'Community Impact')], max_length=64)),
                ('image', models.ImageField(upload_to=ecommerceapp.models._upload_gallery)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_label', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('attendees', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sort', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active', 'sort'], name='ecommerceap_categor_e4c39d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('testimonial', models.TextField()),
                ('product', models.CharField(blank=True, max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=ecommerceapp.models._upload_testimonials)),
                ('verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort'], name='ecommerceap_is_acti_509ab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to=ecommerceapp.models._upload_videos)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=ecommerceapp.models._upload_videos)),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sort'], name='ecommerceap_is_acti_10352c_idx')],
            },
        ),
    ]
