# Generated by Django 5.2.1 on 2025-10-06 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0017_awardrecognition_certification_galleryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('content_markdown', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('tags_csv', models.CharField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='read_time_min',
            new_name='views_count',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='view_count',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/categories/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_csv',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=600),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='ecommerceapp.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='ecommerceap_slug_8af98c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', 'published_at'], name='ecommerceap_is_publ_e0ea59_idx'),
        ),
        migrations.AddField(
            model_name='blogpostversion',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpostversion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ecommerceapp.blogpost'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpostversion',
            unique_together={('post', 'version')},
        ),
    ]
